"""Bundled English and Hindi UI string tables for the courtroom Streamlit app."""

UI_TRANSLATIONS = {
    "en": {
        "lang_title": "### Language / भाषा",
        "select_interface_language": "Select Interface Language",
        "about_app": "**About This App:**",
        "about_desc": "An AI-powered courtroom simulation that helps you:",
        "about_langs": "**Supported Languages:**",
        "header_title": "⚖️ AI Courtroom Battle Simulator",
        "header_subtitle": "Interactive adversarial legal reasoning · BNS 2023 · Powered by Databricks LLaMA",
        "describe_case": "Describe your case",
        "case_placeholder": "e.g. My client is accused of theft under BNS Section 303. The only evidence is CCTV footage from a store, however the footage quality is poor and the identity is unclear. There are no eyewitnesses...",
        "start_hearing": "⚔️ Start Hearing",
        "warning_enter_case": " Please enter your case description before running the simulation.",
        "spinner_init": "🔄 Initializing interactive hearing...",
        "loader_hearing_title": "Counsel is entering the courtroom",
        "loader_round_title": "Counsel is presenting your case",
        "sim_failed": " Simulation failed",
        "legal_context": " Legal Context Retrieved (RAG)",
        "round_completed": "Completed",
        "opposing_counsel": " Opposing Counsel",
        "defense_lawyer": " Defense Lawyer",
        "judges_ruling": " Judge's Ruling",
        "round": "Round",
        "defense": "Defense",
        "prosecution": "Prosecution",
        "round_winner": "Round Winner",
        "defense_strengths": " Defense strengths",
        "defense_weaknesses": " Defense weaknesses",
        "reasoning": " Reasoning",
        "your_turn": "Your Turn",
        "opposing_attack": "⚔️ Opposing Counsel's Attack",
        "choose_strategy": "###  Your Defense Lawyer suggests 3 strategies. Choose one:",
        "option": "Option",
        "strength": "💡 Strength",
        "select_option": "Select Option",
        "please_select_strategy": " Please select one of the strategies above to proceed",
        "evidence_required": "### Evidence Required",
        "evidence_reason_default": "Additional evidence will strengthen your case",
        "upload_evidence": "Upload evidence (PDF, Images)",
        "proceed_argument": " Proceed with this argument",
        "spinner_process_argument": "⚖️ Processing your argument...",
        "error_processing_round": "Error processing round",
        "end_hearing": " End Hearing",
        "cred_check": "Evidence Credibility Check",
        "ai_evidence_analysis_complete": "###  AI Evidence Analysis Complete",
        "evidence_analysis_info": "Our AI has analyzed the uploaded evidence for credibility, relevance, and potential issues. Review the analysis below before proceeding.",
        "evidence_document": " Evidence Document",
        "credibility_score": "Credibility Score",
        "relevance": "Relevance",
        "authenticity_concerns": " Authenticity Concerns",
        "admissibility_issues": "⚖️ Admissibility Issues",
        "strategic_value": " Strategic Value",
        "red_flags_identified": " Red Flags Identified",
        "recommendations": " Recommendations",
        "overall_assessment": "Overall Assessment",
        "skip_evidence": " Skip Evidence",
        "spinner_without_evidence": "⚖️ Proceeding without evidence...",
        "use_this_evidence": " Use This Evidence",
        "spinner_incorporate": " Incorporating evidence into argument...",
        "evidence_needed": "Evidence Needed",
        "evidence_request": " Evidence Request",
        "evidence_request_default": "Please upload evidence documents to strengthen your case",
        "submit_evidence_analysis": " Submit Evidence for Analysis",
        "spinner_analyze_evidence": " Analyzing evidence credibility...",
        "hearing_complete": " Hearing Complete!",
        "final_verdict": "🏛️ Final Verdict",
        "win_probability_defense": " Win Probability (Defense)",
        "lose": "Lose",
        "win": "Win",
        "strong_points": " Strong Points",
        "weak_points": " Weak Points",
        "strategy_suggestions": " Strategy Suggestions",
        "start_new_hearing": " Start New Hearing"
    },
    "hi": {
        "lang_title": "###  भाषा",
        "select_interface_language": "इंटरफेस भाषा चुनें",
        "about_app": "**इस ऐप के बारे में:**",
        "about_desc": "यह AI आधारित कोर्टरूम सिमुलेशन आपकी मदद करता है:",
        "about_langs": "**समर्थित भाषाएं:**",
        "header_title": "⚖️ AI कोर्टरूम बैटल सिम्युलेटर",
        "header_subtitle": "इंटरएक्टिव कानूनी तर्क-वितर्क · BNS 2023 · Databricks LLaMA द्वारा संचालित",
        "describe_case": "अपना केस बताएं",
        "case_placeholder": "उदा. मेरे क्लाइंट पर BNS धारा 303 के तहत चोरी का आरोप है...",
        "start_hearing": "⚔️ सुनवाई शुरू करें",
        "warning_enter_case": " कृपया सिमुलेशन चलाने से पहले केस विवरण दर्ज करें।",
        "spinner_init": " इंटरएक्टिव सुनवाई शुरू की जा रही है...",
        "loader_hearing_title": "वकील कक्ष में प्रवेश कर रहे हैं",
        "loader_round_title": "वकील आपका पक्ष रख रहे हैं",
        "sim_failed": " सिमुलेशन विफल",
        "legal_context": " प्राप्त कानूनी संदर्भ (RAG)",
        "round_completed": "पूर्ण",
        "opposing_counsel": "⚔️ विरोधी वकील",
        "defense_lawyer": " बचाव पक्ष वकील",
        "judges_ruling": " न्यायाधीश का निर्णय",
        "round": "राउंड",
        "defense": "बचाव",
        "prosecution": "अभियोजन",
        "round_winner": "राउंड विजेता",
        "defense_strengths": " बचाव की ताकत",
        "defense_weaknesses": " बचाव की कमजोरियां",
        "reasoning": " तर्क",
        "your_turn": "आपकी बारी",
        "opposing_attack": "⚔️ विरोधी वकील का हमला",
        "choose_strategy": "###  आपका बचाव वकील 3 रणनीतियां सुझाता है। एक चुनें:",
        "option": "विकल्प",
        "strength": " मजबूती",
        "select_option": "विकल्प चुनें",
        "please_select_strategy": "ℹ आगे बढ़ने के लिए ऊपर दी गई रणनीतियों में से एक चुनें",
        "evidence_required": "###  साक्ष्य आवश्यक",
        "evidence_reason_default": "अतिरिक्त साक्ष्य आपके केस को मजबूत करेंगे",
        "upload_evidence": "साक्ष्य अपलोड करें (PDF, Images)",
        "proceed_argument": " इस तर्क के साथ आगे बढ़ें",
        "spinner_process_argument": "⚖️ आपके तर्क को प्रोसेस किया जा रहा है...",
        "error_processing_round": "राउंड प्रोसेसिंग में त्रुटि",
        "end_hearing": " सुनवाई समाप्त करें",
        "cred_check": "साक्ष्य विश्वसनीयता जांच",
        "ai_evidence_analysis_complete": "###  AI साक्ष्य विश्लेषण पूरा",
        "evidence_analysis_info": "AI ने अपलोड किए गए साक्ष्य की विश्वसनीयता, प्रासंगिकता और संभावित समस्याओं का विश्लेषण किया है। आगे बढ़ने से पहले समीक्षा करें।",
        "evidence_document": " साक्ष्य दस्तावेज",
        "credibility_score": "विश्वसनीयता स्कोर",
        "relevance": " प्रासंगिकता",
        "authenticity_concerns": " प्रामाणिकता संबंधी चिंताएं",
        "admissibility_issues": "⚖️ स्वीकार्यता संबंधी मुद्दे",
        "strategic_value": " रणनीतिक मूल्य",
        "red_flags_identified": " पहचाने गए रेड फ्लैग्स",
        "recommendations": " सिफारिशें",
        "overall_assessment": "समग्र आकलन",
        "skip_evidence": "⏭ साक्ष्य छोड़ें",
        "spinner_without_evidence": "⚖️ साक्ष्य के बिना आगे बढ़ रहे हैं...",
        "use_this_evidence": " इस साक्ष्य का उपयोग करें",
        "spinner_incorporate": " साक्ष्य को तर्क में शामिल किया जा रहा है...",
        "evidence_needed": "साक्ष्य चाहिए",
        "evidence_request": " साक्ष्य अनुरोध",
        "evidence_request_default": "कृपया अपना केस मजबूत करने के लिए साक्ष्य दस्तावेज़ अपलोड करें",
        "submit_evidence_analysis": " विश्लेषण के लिए साक्ष्य सबमिट करें",
        "spinner_analyze_evidence": " साक्ष्य विश्वसनीयता का विश्लेषण किया जा रहा है...",
        "hearing_complete": " सुनवाई पूर्ण!",
        "final_verdict": "🏛️ अंतिम निर्णय",
        "win_probability_defense": " जीत की संभावना (बचाव)",
        "lose": "हार",
        "win": "जीत",
        "strong_points": " मजबूत बिंदु",
        "weak_points": " कमजोर बिंदु",
        "strategy_suggestions": " रणनीति सुझाव",
        "start_new_hearing": " नई सुनवाई शुरू करें"
    }
}
